switch("cc", "clang")
switch("checks", "off")
switch("d", "danger")
switch("d", "noSignalHandler")
switch("d", "release")
switch("d", "ssl")
switch("d", "useMalloc")
switch("debugInfo", "off")
switch("exceptions", "goto")
switch("lineTrace", "off")
switch("mm", "orc")
switch("opt", "size")
switch("panics", "on")
switch("stackTrace", "off")
switch("threads", "off")
switch("w", "on")
switch("passC", "-Ilua/src -Ilmdb -Izstd/lib -Ilibressl/include -Itweetnacl")
#switch("dynlibOverride", "ssl")
