switch("cc", "clang")
switch("clang.exe", "emcc")
switch("clang.linkerexe", "emcc")
switch("d", "noSignalHandler")
switch("d", "useMalloc")
switch("exceptions", "goto")
switch("mm", "orc")
switch("opt", "size")
switch("panics", "on")
switch("threads", "off")
switch("w", "on")

switch("d", "danger")
switch("lineTrace", "off")
switch("stackTrace", "off")
switch("checks", "off")

switch("d", "ssl")
