export const TEXT_EXPLANATIONS: Record<string, string[]> = {
  "01-intro/01-yas": [
    "YAS keeps terminal work intact while making applications, files, language tools, media, routes, and durable workspace state available through the same server. It expands the remote session without replacing the shell.",
    "Pierre Carrier presents this work for Indent. The links open the corresponding sites in a new tab.",
  ],
  "01-intro/02-remote-workspace": [
    "A productive remote session spans many kinds of state, not just stdin and stdout. YAS gives those tools a common lifecycle and recovery model.",
    "Independent tunnels make each tool solve authentication, discovery, reconnect, and cleanup again. They also leave users to reconcile several partial views of the same machine.",
    "A byte transcript cannot recreate a process, parsed terminal grid, open window, or repository watch. Viewer-specific pacing also keeps a slow phone from degrading a fast laptop.",
  ],
  "01-intro/03-live": [
    "Clients subscribe to resources instead of downloading an entire workspace. Opening fewer watches reduces startup work and ongoing traffic.",
    "Each interface opens an independent session over the same server-owned resources. They collaborate on current state without sharing a viewport or connection.",
    "The snapshot is capped so recovery has a predictable memory and latency cost. Ordered changes then keep the client current without repeatedly sending the whole resource.",
    "Operation IDs settle ambiguous retries, state cursors expose whether replay is possible, and session-owned resources have explicit teardown rules. Reconnect never has to guess what survived.",
  ],
  "01-intro/04-scope": [
    "Core negotiates the session, Transfer carries large bodies, Relay reaches another server, and Client reports connected sessions. Together they establish and recover the path before feature work begins.",
    "These families cover text terminals, individual GUI windows, clipboard and drag-and-drop, desktop services, audio/video, and exact font data. They are the user-visible remote desktop surface without reducing it to one screen recording.",
    "Filesystem edits files, Git exposes repository structure, and LSP supplies language intelligence. Each keeps its own semantics instead of sending formatted shell output.",
    "KV stores small durable values such as routes, layout, and extension intent. It is workspace memory, not source code storage.",
    "Process runs programs, Network reaches endpoints beside the server, Channel gives tools message-oriented rendezvous, and Extension supervises deployed modules. These are execution building blocks rather than terminal tricks.",
    "Events provides a loss-explicit diagnostic journal, while Environment reports the immutable process environment captured at boot. Both expose server state for inspection rather than manipulation.",
  ],
  "01-intro/05-constraints": [
    "Linux currently has every feature, while the macOS and Windows builds currently cover persistent PTY multiplexing. The protocol is broader than the feature set shipped on those two platforms today.",
    "The browser client is responsive and adaptive rather than desktop-only. Each device opens views sized and paced for its own screen and decoder.",
    "Input methods, ownership, device coordinates, and media timing cross the protocol explicitly. That preserves native behavior instead of approximating it with browser shortcuts.",
    "Rows, pixels, frame rate, quality, and queue targets belong to a view, not to the shared resource. A local browser and a distant phone can therefore use different tradeoffs simultaneously.",
    "The reliable stream carries authoritative state and recovery points. Only families with an explicit loss strategy may use the optional datagram lane.",
    "YAS includes its own persistence and software fallbacks. A database, host display session, or accelerator can improve a deployment but is not required to start one.",
    "The implementations exist, but release sign-off still needs the archived cross-platform, lifecycle, browser, transport, load, latency, and sustained-fuzz matrix. This distinguishes feature presence from production qualification.",
  ],

  "02-protocol/01-architecture": [
    "HELLO creates one independently negotiated client session, while the server keeps the resources themselves. An edge may authenticate or adapt framing, but it does not become the owner of terminals, routes, fonts, or workspace state.",
  ],
  "02-protocol/02-core": [
    "HELLO selects the compatible protocol and family versions, codecs, limits, and server platform once. Unsupported operations are absent from the negotiated catalogue rather than failing by surprise later.",
    "A request admitted by the server always ends in one correlated Result, including errors and cancellation races. Silence is never interpreted as success.",
    "Numeric IDs stay stable across implementations and releases. Packet captures and event traces can identify an operation without relying on localized names or source-code enums.",
    "One negotiated cap covers all receive-side material waiting to be decoded or applied. A peer cannot evade memory limits by spreading data across several frame types.",
    "Datagrams supplement an already established reliable session; they never replace its handshake or authority. A family may use them only when it defines loss and recovery behavior.",
    "PING reports round-trip time and clock offset; CANCEL still receives a final Result. GOAWAY drains admitted work, and SHUTDOWN queues its Result before announcing server closure.",
  ],
  "02-protocol/03-transfer": [
    "Transfer centralizes flow control and chunking for bodies too large for control frames. The same tested mechanism serves files, stdio, tunnels, fonts, clipboard payloads, and messages.",
    "Byte mode preserves offsets; message mode also preserves boundaries. Credit, close, and reset are protocol events, so neither side infers completion from a stalled connection.",
    "Transfer deliberately does not interpret its contents. The family that opened it validates offsets, permissions, media type, and final meaning.",
    "End-of-stream says all transfer bytes arrived; it does not make them durable. Filesystem performs its own hash, precondition, and atomic-commit checks afterward.",
    "SENSITIVE is a diagnostic classification that suppresses routine payload logging. Encryption and peer authentication still come from the chosen transport and credentials.",
  ],
  "02-protocol/04-state": [
    "A watch cursor names the last state the client applied. That makes resume a precise request rather than a guess based on elapsed time.",
    "The server may merge pending changes or replay retained ones when the result remains complete and ordered. If the requested history is gone, RESET says so before a new snapshot replaces it.",
    "A mutation's stable operation ID survives a lost response and reconnect. Repeating the request returns the original outcome instead of applying the change again.",
  ],
  "02-protocol/05-relay-client": [
    "Named routes turn destinations into a stable user choice; local instance names also isolate sockets and persistent state on one machine. --on changes only the destination for that invocation.",
    "An SSH route can bootstrap YAS and reuse familiar OpenSSH identity and host settings. Trust-on-first-use records the host key so a later change is visible instead of silently accepted.",
    "The Relay catalogue exposes route names and availability without embedding connector URIs, private keys, or passphrases. A normal full-authority session may still read the KV configuration where saved routes are stored; the catalogue itself is not a credential leak.",
    "CONNECT starts a fresh protocol session to the destination. Sending the preface and HELLO with the request can eliminate one network round trip on a cold route.",
    "The home server forwards the nested session as an opaque duplex byte stream and preserves half-close. Resource handles and catalogues remain meaningful only to the destination that issued them.",
    "Routes can compose several connector types, including another Relay. Every new hop performs its own negotiation, so capabilities are never assumed from the previous link.",
  ],
  "02-protocol/06-clients": [
    "Each HELLO contributes a client identity and origin record, then the server maintains connection and idle timestamps. This distinguishes an active collaborator from an abandoned tab.",
    "Totals answer how much a session has transferred; sampled rates answer what it is consuming now. A lifetime average would hide bursts and long-idle connections.",
    "The client catalogue includes mounted view dimensions and active state watches. It shows what a session is consuming without exposing the content itself.",
    "The browser presents the catalogue for people, and the CLI exposes the same typed records for scripts. Neither needs to infer clients from operating-system sockets.",
    "DISCONNECT is a correlated operation: the caller receives its Result before the target gets a reasoned GOAWAY. This preserves observable ordering during administrative cleanup.",
    "Client disconnect tears down one session and its session-owned resources. Core SHUTDOWN is intentionally separate because it stops the entire server.",
  ],

  "03-terminal/01-lifecycle": [
    "The catalogue exposes both stable identity and live terminal state, including the current generation and exit record. A user can find the right terminal without attaching to every PTY.",
    "Launch records preserve how the PTY was created, including working-directory source and environment policy. Restart can therefore reproduce the command instead of reconstructing it from screen text.",
    "A restart increments the generation before new output is accepted. Late frames from the previous process cannot contaminate the replacement terminal.",
    "Signals target the process group, while deadlines and dead-man switches handle unattended work. Wait can stop on process exit or on a server-side text pattern.",
    "Exit changes lifecycle state; it does not immediately erase the parsed grid or journal. The terminal remains useful for inspection and deliberate restart.",
    "Native attach supplies normal raw-TTY interaction, while YASREC1 records timestamped terminal activity for later playback. Both address the same retained terminal resource.",
  ],
  "03-terminal/02-views": [
    "Geometry, scroll, focus, rendering pace, display density, and queue targets belong to one mounted view. Reconfiguring a phone does not resize or unfocus a laptop's view.",
    "Clients observe the same PTY and parsed terminal generation but maintain independent presentation state. Sharing a terminal does not mean fighting over one scroll position.",
    "A keyframe can stand alone; a delta names the state it follows or an explicit older base. Final state lets a closing view finish consistently rather than ending mid-update.",
    "Presentation feedback separates transport delivery from actual paint progress. The server can see decoder/render backlog and available frame slots instead of guessing from TCP throughput.",
    "The scheduler gives interactive focused views first claim on scarce capacity, then previews, then bulk transfers. Priority follows attention without making background work impossible.",
    "Local echo is predicted only when the negotiated PTY modes guarantee the same bytes will be echoed. Password prompts, raw mode, and other unsafe cases bypass prediction.",
  ],
  "03-terminal/03-content": [
    "Foreground and background sources plus the core style flags are represented directly in each cell. Wide-cell continuation is explicit, so the renderer does not rediscover terminal layout rules.",
    "Cells refer to complete grapheme content, including combining marks, double-width characters, emoji, and overflow strings. Unicode rendering is not reduced to one code point per cell.",
    "The frame includes the cursor, active modes, viewport, scrollback metadata, line attributes, title, and OSC 7 working directory. These values affect interaction as well as appearance.",
    "OSC 8 link identity survives wrapping, and visible URLs can be detected when applications omit metadata. Opening still follows an explicit allow, confirm, or deny policy.",
    "The server publishes the faces and metrics used to lay out cells and may export permitted font bytes by hash. The browser can match geometry instead of substituting a vaguely similar font.",
    "The fast path builds renderer-ready vertices in WASM and can feed WebGPU without extra copies. WebGL2 and Canvas 2D remain fallbacks, while interaction layers stay separate from the cell grid.",
  ],
  "03-terminal/04-input": [
    "Key events are translated using current terminal modes, so cursor keys and function keys emit the correct escape sequences. Literal control bytes remain possible when that is the intended input.",
    "The browser sends the committed composition string as UTF-8 after the input method finishes. Accented, CJK, and multi-codepoint text are not reverse-engineered into synthetic key presses.",
    "YAS supports the common terminal mouse encodings and distinguishes press, release, movement, hover, click, and wheel. Pixel mode retains precision when a terminal application requests it.",
    "The client can maintain a text selection independently of application mouse reporting. Holding a selection gesture therefore need not inject mouse events into vim, tmux, or another TUI.",
    "When a Wayland selection owns the session clipboard, paste reads that live owner; otherwise it reads the host clipboard. The client never falls back to an older cached value after ownership changes.",
    "Automation uses the same explicit operations as a person, including geometry, focus, mouse, paste, and pointer state. Agents do not need to fake browser DOM events or parse screenshots.",
  ],
  "03-terminal/05-history": [
    "SHOW asks the server to render its current parsed grid as text or ANSI. An optional resize lets a script request the same layout it wants to inspect.",
    "History queries address the combined scrollback and viewport by stable offsets or continuation cursor. Page limits keep a large terminal from becoming one unbounded response.",
    "Search can rank across title, visible cells, and history, or run ripgrep-compatible matching. Soft-wrapped terminal rows are rejoined so one logical line is searchable as one line.",
    "Copy reads cell ranges rather than OCR text. Overflow graphemes and link annotations therefore survive extraction.",
    "OSC 133 shell integration turns prompt, command, output, and exit boundaries into journal records. Stable command IDs make timing and status usable after the screen has scrolled away.",
    "The server can wait for command completion or regex matches and return bounded output plus a continuation cursor. A caller does not need to poll and repeatedly scrape the viewport.",
  ],
  "03-terminal/06-codec": [
    "The common cell representation is fixed-width and directly consumable by the renderer. Twelve bytes cover the hot layout fields; uncommon long text and links live in side tables.",
    "For each changed region, the encoder compares several legal shapes and chooses the smallest representation. Copies are especially cheap for terminal scrolling.",
    "Transposing byte planes groups similar fields before compression. LZ4 is used only when the complete encoded result saves at least eight bytes.",
    "Large graphemes, hyperlink mappings, and line metadata are versioned side structures. An older client can skip unknown optional tables without corrupting the base grid.",
    "Both encoded chunks and declared decoded sizes are capped and checked before allocation. Malformed or adversarial frames cannot request arbitrary memory.",
    "Every delta identifies a verified ancestor and stays inside a sequence window. If the base is unavailable, the client requests or waits for a self-contained keyframe.",
  ],

  "04-wayland/01-windows": [
    "Each top-level application window has a stable Surface handle and live metadata, rather than being a rectangle inside one desktop video. Input and lifecycle operations can target it directly.",
    "The server stamps the sandbox, application, and instance identity at launch. Terminal and Process can place a new program into an app endpoint so its windows are attributed correctly.",
    "Titles update live, while icon lookup uses the trusted launch identity and session-scoped desktop entries. A client cannot gain a convincing identity merely by setting its own Wayland app_id.",
    "Child popups and subsurfaces remain correctly positioned in the top-level composition. Only independent top levels become separate workspace panes.",
    "An activation request sets visible attention state but does not force focus away from the user. The browser remains the authority for which pane becomes active.",
    "Catalogue and control operations support window switching as well as automated capture and recording. They address the application window, not a whole remote desktop.",
  ],
  "04-wayland/02-shell": [
    "The compositor implements the current core shell, sizing, presentation, decoration, activation, scaling, and cursor protocols expected by modern clients. Applications see normal Wayland capabilities without a physical display.",
    "Relative motion, confinement, IME, clipboard, primary selection, drag-and-drop, and touch use their native protocol objects. Games, editors, and toolkits do not have to fall back to simplistic input.",
    "Configure and acknowledgement preserve the normal xdg-shell resize contract, including maximize, fullscreen, and parent relationships. Minimize is a no-op because visibility is controlled independently by each remote view.",
    "Popup placement, repositioning, grabs, dismissal, and hit testing remain in the compositor. Menus and nested menus therefore behave like application UI rather than separate streamed windows.",
    "xdg-foreign supplies stable parent handles for portal dialogs. A camera or screencast prompt can be associated with the window that requested it.",
    "Native Wayland programs run directly; xwayland-satellite optionally bridges X11 applications. The target includes mainstream Chrome, Electron, and mpv workloads, not a toy widget set.",
  ],
  "04-wayland/03-input": [
    "Physical-key identity is distinct from text input and includes press, release, repeat, and modifiers. Focus loss synthesizes any missing releases so applications never retain stuck keys.",
    "Committed text and IME preedit are separate messages, including the preedit cursor and selection. Non-ASCII input follows the text-input path instead of pretending to be a keyboard layout.",
    "Pointer state includes absolute and relative motion, five buttons, continuous axes, discrete wheel steps, source, and stop. Constraints and relative mode remain explicit.",
    "A cursor can reference a standard name or carry custom RGBA pixels, hotspot, and scale; hidden is also a real state. The viewer can reproduce application cursor intent exactly.",
    "Native multitouch preserves several simultaneous contact IDs. Optional compatibility gestures translate touch into pointer actions only when a client requests that behavior.",
    "Signed 32.32 uses a 64-bit integer with a signed 32-bit whole part and a 32-bit fraction: roughly ±2.1 billion pixels with deterministic subpixel precision. Positions stay in the app's native composited frame even when video is scaled, and remote-user marks expire on release, disconnect, or timeout.",
  ],
  "04-wayland/04-selection": [
    "Clipboard, primary selection, and drag-and-drop each track the current owner, offered MIME forms, revision, and lifecycle. Multiple items and formats remain available until ownership actually changes.",
    "Small values fit in control messages; larger ones use flow-controlled Transfer and staged commit. Size does not change ownership or atomicity semantics.",
    "The browser bridge supports text and images while choosing a representation browsers can reliably expose. If it cannot publish a complete current value, it fails instead of truncating or serving an old one.",
    "For Ctrl+V, YAS publishes the browser value before releasing the shortcut to the application, avoiding a race with paste. An empty browser clipboard does not erase a valid Wayland-owned selection.",
    "The session can copy between two surfaces or between a surface and terminal even if the local operating-system clipboard rejects a write. The host clipboard is an integration point, not the source of truth.",
    "Drag events preserve hover lifecycle and expose staged remote files through a live text/uri-list. Cancellation and leaving a target clean up the offer explicitly.",
  ],
  "04-wayland/05-video": [
    "The compositor imports shared-memory and DMA-BUF buffers in common channel orders, reuses committed content, and processes accumulated damage. Vulkan accelerates composition when available; the CPU path preserves correctness without it.",
    "A view declares its output size, display density, cadence, latency target, decoder room, quality, chroma, and keyframe policy. These choices never force another viewer to use the same stream.",
    "Codec and chroma are negotiated per view, then the server chooses the best available implementation. The fallback chain reaches software, so hardware acceleration is an optimization rather than a requirement.",
    "Obsolete frames may be discarded, but configuration, dependencies, end-of-stream, and recovery points remain reliable. Credit reflects actual progress, and presentation timestamps smooth the newest usable frame.",
    "Still capture produces PNG or AVIF, while recording can preserve raw H.264 Annex B or AV1 OBU output. Size, cadence, codec, and timing are explicit recording controls.",
  ],

  "05-desktop/01-desktop": [
    "Desktop services remain structured objects with revisions and actions. A browser can render them appropriately instead of decoding them from a full-screen video.",
    "StatusNotifier carries the normal tray icon variants, tooltip, activation, alternate activation, and scrolling. Applications keep their real tray behavior outside a traditional panel.",
    "DBusMenu is normalized into a bounded tree with icon data and revisions. An action names the revision it was rendered from, so clicking a stale menu cannot invoke the wrong item.",
    "Notifications retain replacement IDs, expiry, buttons, inline replies, progress, and close reasons in addition to text and icons. The application receives the same lifecycle feedback it expects locally.",
    "The browser chooses a presentation suited to urgency and visibility: persistent status, active cards, transient toasts, or opt-in operating-system notification. The protocol state is independent of that choice.",
    "Remote applications use an isolated session bus containing only the desktop services YAS provides. The host user's existing D-Bus session and its unrelated services are not exposed.",
  ],
  "05-desktop/02-media": [
    "Server playback can reach the viewer, while microphone and camera inputs are temporary resources leased to a requesting application. Closing or revoking the lease stops that access.",
    "Permission is represented in acquisition state rather than hidden in browser UI. Denying a microphone does not tear down the window, audio output, or unrelated capabilities.",
    "Portal requests include their deadlines, candidate choices, and final selection. The browser can present consent for the specific window or screencast source being requested.",
    "MPRIS exposes a player's metadata and exact current capabilities as live state. Controls include the revision the user saw, preventing actions against an obsolete track or player state.",
    "Video and audio formats are negotiated, and every packet retains capture and intended presentation time. Timing stays meaningful across buffering and transport variation.",
    "The media path favors recent frames while keeping configuration, keyframes, leases, and terminal status reliable. Playout reports tell the server what the viewer actually heard or displayed.",
    "YAS reports the difference between audible and visible latency back to PipeWire. Applications that understand A/V synchronization can compensate without forcing YAS to delay every video frame.",
  ],
  "05-desktop/03-fonts": [
    "The catalogue describes installed faces with the properties a shaping and layout engine needs, not just family names. Clients can choose the same face the server selected.",
    "Queries cover monospace, variable axes, color support, download eligibility, localized names, and Unicode coverage. This supports terminal grids and application text across scripts.",
    "A server policy decision and the font's OS/2 embedding permission must both allow export. Being installed does not automatically make a face downloadable.",
    "Small metadata or font bodies may be inline; large bodies use Transfer. BLAKE3 verifies that downloaded bytes match the advertised immutable face.",
    "A content hash remains valid when the same font is reached after a restart or through another route. Browsers avoid downloading identical bytes repeatedly.",
    "Terminal rendering uses the exact server-reported cell metrics and fetched face when allowed. Font access remains an ordinary server family, not an undocumented edge endpoint.",
  ],

  "06-workspace/01-filesystem": [
    "A Filesystem root can come from an absolute platform path, another resource's working directory, one file, or isolated drag staging. Clients do not need an operating-system mount.",
    "Paths are component vectors using the server platform's byte model. The protocol does not silently clean traversal, separators, case, or encoding into different paths.",
    "A watch starts with metadata and then reports structural and content changes, including moves. Large contents stay lazy, while hashes and inline thresholds make synchronization bounded.",
    "Typed reads and searches return pages with continuation cursors rather than formatted command text. Link targets, hashes, and content retain their distinct result types.",
    "The server applies ignore and hidden-file policy while preserving Git awareness and rename identity. A reset explicitly tells the client when watcher history no longer supports incremental recovery.",
    "Writes are uploaded, hashed, checked, and atomically committed; a batch extends the same preconditions across several filesystem operations. Concurrent edits fail visibly instead of partially overwriting a tree.",
  ],
  "06-workspace/02-git": [
    "The repository watch reports important refs and working state as revisions change. A client can stay current without periodically running and parsing git status.",
    "Each query returns typed repository objects, identities, ranges, and relationships. The list covers navigation, history, content, change analysis, discovery, and worktree state.",
    "Object format is explicit, so SHA-1 and SHA-256 repositories retain their native identity. Pagination and Transfer keep large logs, blobs, and patches bounded.",
    "A watched query records the refs it depends on and reruns when they change. No arbitrary shell or long-lived command tunnel is needed for live repository UI.",
    "Patch records distinguish files, rows, spans, omitted gaps, merge ancestry, and binary data. Clients can render or analyze changes without reverse-parsing unified diff text.",
    "Fetch uses an operation ID for retry safety and emits structured progress phases and counters. The final per-ref records make partial remote outcomes explicit.",
  ],
  "06-workspace/03-lsp": [
    "YAS alone speaks JSON-RPC to each language server and translates its answers into protocol records. Backend request IDs and UTF-16 coordinates remain private implementation details.",
    "A project may be rooted from Filesystem, an exact platform path, or a terminal working directory. Profiles select known server settings, while discovery can choose one automatically.",
    "The watch reports backend health, resource use, capabilities, progress, diagnostics, and the shared unsaved document set. Several clients see one coherent language-server workspace.",
    "Navigation, help, completion, refactoring, formatting, and signature results cross the wire as typed values. Clients do not parse editor-specific prose or raw LSP JSON.",
    "Protocol coordinates are zero-based UTF-8 byte offsets, and results identify the source revision and hash they describe. A caller can reject an answer after the document changes.",
    "Unsaved buffers use compare-and-swap or staged replacement to avoid lost edits. Rename produces a reviewed edit plan; Filesystem remains responsible for committing it.",
  ],
  "06-workspace/04-ide": [
    "Explorer and Search consume Filesystem watches and queries, while Problems consumes LSP diagnostics. The panels update from the same state available to the CLI and agents.",
    "Code, changes, web content, terminals, and remote applications are peers in one tiling system. Focus and layout do not split into separate desktop and IDE worlds.",
    "A save names the revision it edited and commits atomically. If another client changed the file first, the editor surfaces a conflict instead of overwriting it.",
    "Repository panels use typed Git objects for history and changes. Human-facing command formatting is never an API boundary.",
    "The LSP family supplies revision-bound records for the common editor intelligence surface. The browser only presents those records and applies accepted edits through Filesystem.",
    "Each family keeps a clear job: Git and LSP analyze, Filesystem changes the tree, and Process or Terminal runs arbitrary tools. The IDE composes them without blurring authority or recovery semantics.",
  ],
  "06-workspace/05-kv": [
    "Namespaces group durable binary keys by prefix, and watches use bytewise lexical order. Extensions and workspace UI can share small state without inventing files.",
    "Hashes detect content identity, revisions order changes, timestamps aid presentation, and small values can ride inline. A listing can describe entries without downloading every body.",
    "Large values are uploaded through bounded Transfer and verified by hash before use. The key/value semantics remain the same regardless of body size.",
    "Single-key and batch mutations can require an expected revision or hash and carry retry-safe operation IDs. A transaction either applies under those conditions or reports the conflict.",
    "The server persists completed operation outcomes as well as values. A reconnect after server restart can retry without duplicating a durable mutation.",
    "KV is for compact shared intent such as saved routes, layouts, and deployments. User documents and source trees remain Filesystem resources.",
  ],

  "07-execution/01-process": [
    "The argv vector is passed directly, so quoting and shell expansion never change it unless the user explicitly launches a shell. Working directory may reference another YAS resource, and an app endpoint attributes any GUI windows.",
    "Each standard stream is a bounded byte Transfer with a lifetime offset. Merging stderr is an explicit launch choice rather than an accidental property of a terminal.",
    "The watch exposes stable launch identity, operating-system PID, owner session, detach policy, stream positions, lifecycle, exit, and retained history. Clients need not infer process state from EOF.",
    "A new observer begins at a named offset and gets GAP if older bytes were discarded. Input has one owner to prevent interleaving, while output permits many observers.",
    "Control operations distinguish signals, graceful termination, forceful kill, detach, and wait. Session-owned processes clean up with their client unless marked detachable.",
    "The stable operation ID records the outcome of launch. Retrying after a lost Result returns that outcome instead of starting a second process.",
  ],
  "07-execution/02-network": [
    "The server can open stream, datagram, sequenced-packet, and Windows pipe endpoints, optionally wrapping a connection in TLS with SNI and ALPN. The endpoint originates from the server's network namespace.",
    "Network transports bytes or messages and does not reimplement higher-level protocols. Client libraries continue to speak HTTP, DNS, PostgreSQL, or WebSocket normally.",
    "Forwarding maps familiar local-listener workflows onto Network resources and also supports UDP. Saved definitions make useful tunnels persistent workspace intent.",
    "SOCKS5 lets unmodified client software choose destinations dynamically. Server-side name resolution preserves the remote machine's DNS view.",
    "A caller can require native datagrams, prefer them, or explicitly accept a reliable tunnel. Sequence and drop reporting expose changed behavior; oversized messages are rejected rather than invisibly fragmented.",
    "Destination policy limits what remote sessions may open, and listeners default to loopback to avoid accidental public exposure. Broader binding must be deliberate.",
  ],
  "07-execution/03-channel": [
    "A Channel advertises a watched human-readable name and one current listener generation. Metadata lets tools discover the intended schema or purpose.",
    "The handshake pairs a connector with the current listener and returns one bidirectional message-mode Transfer. Credit bounds buffering without losing message boundaries.",
    "The connector names the generation it discovered. If the listener was replaced before accept, the command fails instead of reaching a different tool by accident.",
    "Closing the published listener prevents new connections but does not destroy established conversations. Each conversation ends through its own Transfer close or reset.",
    "The message contents are intentionally application-defined and can carry requests, incremental results, actor mail, or commands. YAS supplies rendezvous and delivery, not a mandatory RPC format.",
    "Channel has one listener and point-to-point conversations; it does not promise brokered topics or fan-out. Terminal remains the correct resource for PTY semantics.",
  ],
  "07-execution/04-extensions": [
    "Extension code runs in the Wasmi or QuickJS runtime and is identified by immutable content hash. A deployment refers to verified bytes rather than a mutable path.",
    "Objects upload into staging, receive hash and format checks, and become visible only at atomic commit. Desired deployment state can then refer to them durably.",
    "The declaration controls runtime arguments, resource limits, retry behavior, persistence, and enablement. A supervisor can reproduce the desired state after failure or reboot.",
    "Each attempt receives an in-process connection that negotiates the normal YAS protocol. It gains no undocumented plugin API beyond the operations its session advertises.",
    "Output and logs support retained replay plus explicit gaps, while interactive commands arrive over named Channel listeners. Supervision and application messaging stay separate.",
    "Deployment and control operations keep deduplication records across restart. A repeated request cannot accidentally install or restart the module twice.",
  ],
  "07-execution/05-events": [
    "The server writes compact typed events into one bounded ring using stable IDs. Capacity is finite by design, so diagnostics cannot grow until they exhaust the host.",
    "Configuration is revisioned and changed with compare-and-swap. Administrators can adjust capacity or enabled event classes without racing another update.",
    "A dump hashes the retained segment, while follow crosses from retained history into live events. GAP identifies the exact point at which requested history was overwritten or an observer fell behind.",
    "Server-side recording writes a selected stream to an explicit path and reports final event and byte counters. Append and retained-history policies are visible controls.",
    "Producers never wait for a diagnostic reader. Slow observers lose ring history and receive GAP instead of slowing terminals, media, or other work.",
    "High-risk payload classes remain off unless explicitly enabled. The default journal describes behavior without copying terminal contents, environment secrets, or arbitrary protocol bodies.",
  ],
  "07-execution/06-environment": [
    "Environment reports the process environment captured when the server started and includes server-derived values such as its effective name. It is not a live view of a calling shell.",
    "Keys and values remain raw byte strings in a deterministic ordering, preserving Windows and Unix data that may not be valid Unicode. Clients choose how to display undecodable bytes.",
    "Small typed records are inline; a larger snapshot uses message-mode Transfer under the same receive bounds. Size does not force lossy redaction or string conversion.",
    "The snapshot is immutable for the life of one server boot and supports only GET. A changed environment requires a new server process, not an in-place mutation or watch.",
    "No secret filtering is attempted, so a reduced-authority viewer could receive credentials by design. The operation is advertised only to full-authority sessions.",
  ],

  "08-delivery/01-transports": [
    "YAS uses native local IPC, conventional remote streams, browser transports, and peer-to-peer WebRTC. The user can choose the reachable link without choosing a different feature subset by default.",
    "Every transport begins with the same preface and HELLO and produces the same negotiated operations. Adapters change envelope framing, not resource meaning.",
    "Requests, Results, authoritative state, and recovery points always have an ordered reliable route. Optional low-latency delivery cannot become the only copy of required state.",
    "Only events explicitly declared eligible by Surface, Media, or native Network can use unordered non-retransmitted datagrams. General control messages and terminal frames cannot drift onto that lane.",
    "The owning family defines whether to drop, supersede, reorder, acknowledge, or recover an eligible event. Transport code does not invent media or network semantics.",
    "Every eligible event also has a reliable encoding for links without datagrams or for recovery. Terminal state always stays on the reliable path because its deltas require ordered ancestry.",
  ],
  "08-delivery/02-topologies": [
    "A proxy can retain authenticated remote connections so the next routed action avoids cold-start work. For sharing, server --share can fold the separate share forwarder into the server process.",
    "Workspace-session data stores the user's route, pane arrangement, focus, and panel state in KV. Reopening a workspace restores intent without claiming that view handles survive across servers.",
    "A handle is opaque and meaningful only to the server session that issued it. Relay never translates a home-server terminal or surface handle into a destination-server handle.",
  ],
  "08-delivery/03-authority": [
    "A normal session acts with the server process's operating-system identity and may invoke every operation advertised in HELLO. It should be treated like shell access to that account, not like a limited web dashboard.",
    "Anyone holding the normal browser passphrase has the same broad authority; it is a bearer secret, not a username. Sharing it grants control rather than merely permission to watch.",
    "The ordinary WebRTC credential negotiates read and write operations. Appending the derived .ro form selects a fixed server-enforced read-only operation catalogue.",
    "The read-only profile exposes observation operations for selected terminal, surface, media, and font resources. It omits discovery and mutation powers rather than relying on disabled UI buttons.",
    "A non-loopback WebSocket would otherwise expose credentials and workspace traffic to the network. YAS therefore requires TLS through WSS for that case.",
    "YAS v1 does not express arbitrary users, roles, or family-by-family policies. Separate server processes under separate OS identities provide the security boundary for mutually untrusted people.",
    "SENSITIVE only asks diagnostics not to record ordinary payload contents. It neither encrypts bytes nor changes which operations a session may invoke.",
  ],
  "08-delivery/04-interfaces": [
    "The browser provides the complete interactive workspace, including terminals, windows, files, code intelligence, routes, and sharing. It consumes the same protocol families as non-browser clients.",
    "The CLI exposes resource-oriented subcommands and machine-usable results. Scripts can address retained terminals, processes, repositories, and surfaces without screen scraping.",
    "Framework bindings mount live terminal and surface views inside an application's own component tree. They preserve the independent-view and lifecycle model rather than embedding a separate remote-desktop page.",
    "The published agent skill teaches software agents the same typed operations and recovery rules. Agent actions remain visible in the same server state a person can inspect.",
  ],
  "08-delivery/05-start": [
    "These commands install YAS with a POSIX shell and then open the workspace. The installer URL is intentionally shown plainly rather than hidden behind curl's silent flags.",
    "These are the native PowerShell equivalents for Windows. irm is PowerShell's standard alias for Invoke-RestMethod.",
    "A normal share lets the guest interact; the derived read-only token limits the advertised operation catalogue for observation. The server, not the browser UI, enforces that difference.",
    "The first useful workspace needs no database, reverse proxy, display server, or GPU. Optional integrations and acceleration can still improve particular deployments.",
  ],
  "08-delivery/06-close": [
    "The Process or Terminal resource remains on the server when the laptop session disappears. A phone opens its own smaller view and resumes from current state instead of inheriting the laptop frame queue.",
    "An individual remote application keeps its live identity and desktop integrations as well as video. The user controls a real window, not an anonymous crop of a desktop recording.",
    "A saved route changes which server receives the operation while the browser and CLI retain the same commands and resource model. The user does not assemble a new collection of tunnels per host.",
    "Each collaborator opens an independent session and view over common server-owned resources. People and automation coordinate through live state without mirroring one person's screen.",
  ],
};
