app = "yas-run"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  YAS_WEBSITE_ADDR = "0.0.0.0:8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "20s"
    interval = "15s"
    method = "GET"
    timeout = "3s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
